name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get repository information
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/mohamedaymenkarmous/test/dispatches \
        -d '{"event_type":"test","client_payload":{"unit":false,"integration":true}}'


#curl -X POST -L -H 'Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mohamedaymenkarmous/test/dispatches -d '{"event_type":"test,"client_payload":{"unit":false,"integration":true}}'

# curl -X POST -L -H 'Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mohamedaymenkarmous/test/actions/workflows/blank.yml/dispatches -d '{"ref":"main","inputs":{}}'
