name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get repository information
      run: |
        # Use the `github_token` to get repository information
        # For example, get the list of pull requests:
        curl -X POST -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mohamedaymenkarmous/test/dispatches -d '{"event_type":"test,"client_payload":{"unit":false,"integration":true}}'
        curl -X POST -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mohamedaymenkarmous/test/actions/workflows/blank.yml/dispatches -d '{"ref":"main","inputs":{}}'
